name: toastify
description: A comprehensive Flutter package that displays multiple types of toast messages with customizable designs and animations.
version: 0.0.2
homepage: https://github.com/lvxduck/toastify

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

